# Site settings
title: i am trask
subtitle: Machine Learning Blog
email: liamtrask@gmail.com
description: "A machine learning craftsmanship blog."
baseurl: ""
url: "https://fastestmk.github.io"
twitter_username: fastestmk
github_username:  fastestmk

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

analytics :
  provider : google
  google:
    tracking_id : 'UA-36138203-3'
  getclicky :
    site_id
