# Site settings
title: i am trask
subtitle: Machine Learning Blog
email: liamtrask@gmail.com
description: "A machine learning craftsmanship blog."
baseurl: ""
url: "https://iamtrask.github.io"
twitter_username: iamtrask
github_username:  iamtrask

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
<<<<<<< HEAD
paginate: 5
exclude: ["node_modules"]
=======
#theme: 
>>>>>>> 5bbaac7daee2c3231b7852e6606580e4589d746c

analytics :
  provider : google
  google:
    tracking_id : 'UA-36138203-3'
  getclicky :
    site_id
