# Site settings
title: fastestmk
email: 
description: ""
baseurl: ""
url: "http://fastestmk.github.io"
twitter_username: fastestmk
github_username:  fastestmk

# Build settings
markdown: kramdown
permalink: pretty
theme: minima

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
